# Feature Engineering

- начинаем с удаления признаков с очень большим количеством пропусков (count NaN > 75%)
- заполняем NaN у оставшихся признаков средним значением
- на V-признаках делаем PCA
- вычисляем TransactionDay = TransactionDT / (24 * 60 * 60), далее используя card1, addr1, d1n (transactionDay - d1) вычисляем uid
- на основе uid группируем признаки и считаем их std, mean
- создаем другие новые признаки D4n, D10n, D15n

In [2]:
import cudf as cd
import cupy as cp
import matplotlib.pyplot as plt
import seaborn as sns
import gc
import numpy as np
import pandas as pd

## 1. Очистка данных и загрузка
На этапе EDA мы проанализировали пропуски. Признаки, где доля `NaN` превышает 75%, не несут ценности и только создают шум. Мы загружаем их список из `nans.json` и сразу исключаем при чтении CSV с помощью `cudf` для экономии RAM и VRAM.

In [3]:
import json

with open("nans.json", "r", encoding="utf-8") as f:
    nans_groups = json.load(f)

In [4]:
cols = [508189, 449124, 460110, 450721, 450909, 508589, 508595, 528353, 528588, 525823, 515614, 551623, 517353, 453249, 552913]
d = [j for row in [nans_groups[f'{i}'] for i in cols] for j in row]

In [5]:
cols_t = ['TransactionID', 'TransactionDT', 'TransactionAmt',
       'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6',
       'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain',
       'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11',
       'C12', 'C13', 'C14', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8',
       'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'M1', 'M2', 'M3', 'M4',
       'M5', 'M6', 'M7', 'M8', 'M9']
cols_v = ['V'+str(x) for x in range(1,340)]; types_v = {}
for c in cols_v: types_v[c] = 'float32' # конвертируем для экономии памяти

train_trans = cd.read_csv(r'../data/raw/train_transaction.csv', usecols=cols_t+['isFraud']+cols_v, dtype=types_v).drop(columns=d)

test_trans = cd.read_csv(r'../data/raw/test_transaction.csv', usecols=cols_t+cols_v, dtype=types_v).drop(columns=d)

## 2. Frequency Encoding
Для категориальных признаков используем частотное кодирование. Это позволяет деревьям решений лучше улавливать редкие категории без раздувания размерности, как при One-Hot Encoding.

In [6]:
for col in train_trans.select_dtypes(include=['str']).columns.to_list():
    freq_map = train_trans[col].value_counts(normalize=True).to_dict()
    train_trans[f'{col}_encoded'] = train_trans[col].map(freq_map)
    test_trans[f'{col}_encoded'] = test_trans[col].map(freq_map)

train_trans = train_trans.drop(columns=train_trans.select_dtypes(include=['str']).columns.to_list())
test_trans = test_trans.drop(columns=test_trans.select_dtypes(include=['str']).columns.to_list())

## 3. Обработка пропусков
Оставшиеся пропуски в числовых признаках заполняем средним значением. Для более сложных признаков (например, `D-features`) в будущем можно использовать групповое заполнение по `uid`, но для базового пайплайна `mean` дает стабильный результат.

In [7]:
train_trans = train_trans.fillna(train_trans.mean(numeric_only=True))
test_trans = test_trans.fillna(test_trans.mean(numeric_only=True))

## 4. Снижение размерности (PCA для V-features)
Признаки `V1 - V339` содержат огромное количество скоррелированных данных и шумов. Мы разбиваем их на подгруппы и применяем PCA с использованием `cuML`. Это позволяет сжать сотни колонок в несколько главных компонент, сохранив долю объясненной дисперсии.

In [8]:
from cuml.decomposition import PCA
from cuml.preprocessing import StandardScaler

cols_w_d1 = ['V281', 'V282', 'V283', 'V288', 'V289', 'V296', 'V300', 'V301', 'V313', 'V314', 'V315']
cols = ['279287', '76073', '168969', '77096', '89164', '314', '12']

features = [f'v_pca_{j}' for j in range(3)]
    
scaler = StandardScaler()
train_scaled = scaler.fit_transform(train_trans[cols_w_d1])
test_scaled = scaler.transform(test_trans[cols_w_d1])

# PCA (сокращаем до 3 главных компонент)
pca = PCA(n_components=3)

train_trans[features] = pca.fit_transform(train_scaled)
test_trans[features] = pca.transform(test_scaled)

train_trans = train_trans.drop(columns=cols_w_d1)
test_trans = test_trans.drop(columns=cols_w_d1)

for i, col in enumerate(cols):
    features = [f'v{i}_pca_{j}' for j in range(3)]
    
    scaler = StandardScaler()
    train_scaled = scaler.fit_transform(train_trans[nans_groups[col]])
    test_scaled = scaler.transform(test_trans[nans_groups[col]])
    
    # PCA (сокращаем до 3 главных компонент)
    pca = PCA(n_components=3)
    
    train_trans[features] = pca.fit_transform(train_scaled)
    test_trans[features] = pca.transform(test_scaled)

    train_trans = train_trans.drop(columns=nans_groups[col])
    test_trans = test_trans.drop(columns=nans_groups[col])
    
    print(f'Доля объясненной дисперсии {i}-ой группы:', pca.explained_variance_ratio_)

Доля объясненной дисперсии 0-ой группы: 0    0.381695
1    0.168242
2    0.125581
dtype: float64
Доля объясненной дисперсии 1-ой группы: 0    0.415292
1    0.120791
2    0.086664
dtype: float32
Доля объясненной дисперсии 2-ой группы: 0    0.412156
1    0.174613
2    0.100988
dtype: float32
Доля объясненной дисперсии 3-ой группы: 0    0.443739
1    0.127080
2    0.082708
dtype: float32
Доля объясненной дисперсии 4-ой группы: 0    0.404442
1    0.128079
2    0.096059
dtype: float32
Доля объясненной дисперсии 5-ой группы: 0    0.363400
1    0.179170
2    0.070698
dtype: float32
Доля объясненной дисперсии 6-ой группы: 0    0.439539
1    0.109495
2    0.095835
dtype: float32

## 5. Генерация `uid` и поведенческих фичей 
* `TransactionDay` и сдвиги `D1n`, `D4n`, `D15n` помогают нормализовать время.
* `uid` — кастомный ключ (`card1` + `addr1` + `D1n`), который позволяет идентифицировать одного пользователя даже при смене аккаунта.
* На основе `uid` мы считаем агрегации (mean, std) для суммы транзакции и дистанций.

In [9]:
train_trans['D1n'] = np.floor(train_trans.TransactionDT / (24*60*60)) - train_trans.D1
train_trans['D4n'] = np.floor(train_trans.TransactionDT / (24*60*60)) - train_trans.D4
train_trans['D10n'] = np.floor(train_trans.TransactionDT / (24*60*60)) - train_trans.D10
train_trans['D15n'] = np.floor(train_trans.TransactionDT / (24*60*60)) - train_trans.D15
train_trans['uid'] = train_trans.card1.astype(str)+'_'+train_trans.addr1.astype(str)+'_'+train_trans.D1n.astype(str)

test_trans['D1n'] = np.floor(test_trans.TransactionDT / (24*60*60)) - test_trans.D1
test_trans['D4n'] = np.floor(test_trans.TransactionDT / (24*60*60)) - test_trans.D4
test_trans['D10n'] = np.floor(test_trans.TransactionDT / (24*60*60)) - test_trans.D10
test_trans['D15n'] = np.floor(test_trans.TransactionDT / (24*60*60)) - test_trans.D15
test_trans['uid'] = test_trans.card1.astype(str)+'_'+test_trans.addr1.astype(str)+'_'+test_trans.D1n.astype(str)

In [10]:
for col in ['D4n', 'D10n', 'D15n', 'TransactionAmt', 'dist1']: 
    train_trans[f'{col}_uid_mean'] = train_trans.groupby('uid')[col].transform('mean')
    train_trans[f'{col}_uid_std'] = train_trans.groupby('uid')[col].transform('std')
    test_trans[f'{col}_uid_mean'] = test_trans.groupby('uid')[col].transform('mean')
    test_trans[f'{col}_uid_std'] = test_trans.groupby('uid')[col].transform('std')

    train_trans[f'{col}_uid_std'].fillna(-1, inplace=True)
    test_trans[f'{col}_uid_std'].fillna(-1, inplace=True)

Перед обучением моделей удаляем признак `uid` для избежания утечки данных при предсказывании на тесте.

In [11]:
train_trans = train_trans.drop(columns='uid')
test_trans = test_trans.drop(columns='uid')

## 6. Обучение и GPU-тюнинг
Используем Optuna для оптимизации гиперпараметров. 
Обучение XGBoost, LightGBM и CatBoost происходит с использованием `device='cuda'` / `task_type='GPU'`, что сокращает время итераций с часов до минут.

P.S.: обучить LightGBM на CUDA не удалось ввиду технических ошибок. Решение для устранения проблемы пока не найдено. Также не удалось запустить CatBoost в Optuna ввиду неправильного разделения потоков, решение пока не найдено.

In [12]:
import optuna
from sklearn.metrics import roc_auc_score
from cuml.model_selection import train_test_split
import xgboost as xgb

X_train, X_val, y_train, y_val = train_test_split(train_trans.drop(columns='isFraud'), train_trans['isFraud'], test_size=0.2)

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 2, 12),
        'n_estimators': trial.suggest_int('n_estimators', 300, 1200, step=50),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
    }
    model = xgb.XGBClassifier(**params, tree_method='hist', device='cuda', random_state=42)
    model.fit(X_train, y_train)
    preds = model.predict_proba(X_val)[:, 1]
    return roc_auc_score(y_val.to_numpy(), preds)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)
print(f'XGB Best parameters: {study.best_params}, Best ROC-AUC CV value: {study.best_value}')

[I 2026-08-24 20:02:35,201] A new study created in memory with name: no-name-ef29fc42-1faa-4d89-b56d-27ad6a40673a
[I 2026-08-24 20:02:41,961] Trial 0 finished with value: 0.9353259577698261 and parameters: {'max_depth': 5, 'n_estimators': 1050, 'learning_rate': 0.016552967966956555}. Best is trial 0 with value: 0.9353259577698261.
[I 2026-08-24 20:02:53,919] Trial 1 finished with value: 0.9623791487470876 and parameters: {'max_depth': 10, 'n_estimators': 550, 'learning_rate': 0.011297979230996732}. Best is trial 1 with value: 0.9623791487470876.
[I 2026-08-24 20:02:55,528] Trial 2 finished with value: 0.9479870247145806 and parameters: {'max_depth': 4, 'n_estimators': 300, 'learning_rate': 0.1961936713706609}. Best is trial 1 with value: 0.9623791487470876.
[I 2026-08-24 20:03:07,969] Trial 3 finished with value: 0.9770692720631816 and parameters: {'max_depth': 10, 'n_estimators': 850, 'learning_rate': 0.15181651919488523}. Best is trial 3 with value: 0.9770692720631816.
[I 2026-08-24 20:03:11,246] Trial 4 finished with value: 0.8896578914585983 and parameters: {'max_depth': 3, 'n_estimators': 750, 'learning_rate': 0.01011568067988115}. Best is trial 3 with value: 0.9770692720631816.
[I 2026-08-24 20:03:14,705] Trial 5 finished with value: 0.9634547449886841 and parameters: {'max_depth': 7, 'n_estimators': 350, 'learning_rate': 0.07249868226271426}. Best is trial 3 with value: 0.9770692720631816.
[I 2026-08-24 20:03:35,334] Trial 6 finished with value: 0.971003251305837 and parameters: {'max_depth': 10, 'n_estimators': 1150, 'learning_rate': 0.011908527839396147}. Best is trial 3 with value: 0.9770692720631816.
[I 2026-08-24 20:03:37,537] Trial 7 finished with value: 0.8890430772369995 and parameters: {'max_depth': 2, 'n_estimators': 600, 'learning_rate': 0.037318361644838545}. Best is trial 3 with value: 0.9770692720631816.
[I 2026-08-24 20:03:42,621] Trial 8 finished with value: 0.9561381172935485 and parameters: {'max_depth': 4, 'n_estimators': 1050, 'learning_rate': 0.08848395985775116}. Best is trial 3 with value: 0.9770692720631816.
[I 2026-08-24 20:03:58,120] Trial 9 finished with value: 0.9787113562366544 and parameters: {'max_depth': 12, 'n_estimators': 700, 'learning_rate': 0.07241085898065909}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:04:19,270] Trial 10 finished with value: 0.9781763054503924 and parameters: {'max_depth': 12, 'n_estimators': 850, 'learning_rate': 0.027688707274985846}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:04:39,623] Trial 11 finished with value: 0.977698792542884 and parameters: {'max_depth': 12, 'n_estimators': 850, 'learning_rate': 0.02963758969657651}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:04:56,131] Trial 12 finished with value: 0.9784057152694856 and parameters: {'max_depth': 12, 'n_estimators': 700, 'learning_rate': 0.04131440636675845}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:05:10,052] Trial 13 finished with value: 0.9786039443186526 and parameters: {'max_depth': 12, 'n_estimators': 600, 'learning_rate': 0.06034377519466201}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:05:15,805] Trial 14 finished with value: 0.9731780736091571 and parameters: {'max_depth': 8, 'n_estimators': 500, 'learning_rate': 0.06686220766771404}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:05:28,901] Trial 15 finished with value: 0.9786232241924304 and parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.10445417584818463}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:05:34,908] Trial 16 finished with value: 0.9774113162680012 and parameters: {'max_depth': 9, 'n_estimators': 450, 'learning_rate': 0.13041482779385566}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:05:47,818] Trial 17 finished with value: 0.9777981692458978 and parameters: {'max_depth': 11, 'n_estimators': 700, 'learning_rate': 0.10446283697116636}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:05:55,993] Trial 18 finished with value: 0.9772788037985576 and parameters: {'max_depth': 7, 'n_estimators': 950, 'learning_rate': 0.1122841903685535}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:06:01,630] Trial 19 finished with value: 0.9723446089070219 and parameters: {'max_depth': 9, 'n_estimators': 400, 'learning_rate': 0.05279148646452179}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:06:14,004] Trial 20 finished with value: 0.9756180105301029 and parameters: {'max_depth': 11, 'n_estimators': 750, 'learning_rate': 0.1918691150658306}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:06:25,982] Trial 21 finished with value: 0.9777896655913806 and parameters: {'max_depth': 11, 'n_estimators': 600, 'learning_rate': 0.05952497845332126}. Best is trial 9 with value: 0.9787113562366544.
[I 2026-08-24 20:06:39,895] Trial 22 finished with value: 0.9788056275818258 and parameters: {'max_depth': 12, 'n_estimators': 650, 'learning_rate': 0.08684299890558757}. Best is trial 22 with value: 0.9788056275818258.
[I 2026-08-24 20:06:52,398] Trial 23 finished with value: 0.9790548004848416 and parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.08242569290499799}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:07:01,618] Trial 24 finished with value: 0.9784721440038988 and parameters: {'max_depth': 9, 'n_estimators': 700, 'learning_rate': 0.08253980216780388}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:07:14,427] Trial 25 finished with value: 0.9772460077562908 and parameters: {'max_depth': 12, 'n_estimators': 500, 'learning_rate': 0.04642124386957867}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:07:26,869] Trial 26 finished with value: 0.9785399928275156 and parameters: {'max_depth': 10, 'n_estimators': 800, 'learning_rate': 0.08288446726983656}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:07:42,507] Trial 27 finished with value: 0.9767312887226595 and parameters: {'max_depth': 11, 'n_estimators': 950, 'learning_rate': 0.14761686295626034}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:07:48,235] Trial 28 finished with value: 0.9641473824197317 and parameters: {'max_depth': 8, 'n_estimators': 500, 'learning_rate': 0.03379077862728449}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:08:01,143] Trial 29 finished with value: 0.9780900640449891 and parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.050407284174492833}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:08:23,389] Trial 30 finished with value: 0.9776625982039424 and parameters: {'max_depth': 12, 'n_estimators': 900, 'learning_rate': 0.023890546001395726}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:08:35,383] Trial 31 finished with value: 0.9774975112514692 and parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.103943082455951}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:08:44,339] Trial 32 finished with value: 0.9781010059061552 and parameters: {'max_depth': 10, 'n_estimators': 550, 'learning_rate': 0.07508184377523015}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:08:55,968] Trial 33 finished with value: 0.9786023807434672 and parameters: {'max_depth': 10, 'n_estimators': 750, 'learning_rate': 0.09497506174637163}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:09:07,760] Trial 34 finished with value: 0.9777428859961397 and parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.12085092053445312}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:09:18,927] Trial 35 finished with value: 0.9774851345304838 and parameters: {'max_depth': 12, 'n_estimators': 550, 'learning_rate': 0.14225533733712098}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:09:30,469] Trial 36 finished with value: 0.976987068311108 and parameters: {'max_depth': 10, 'n_estimators': 800, 'learning_rate': 0.17977355998798913}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:09:34,880] Trial 37 finished with value: 0.9717885996720025 and parameters: {'max_depth': 9, 'n_estimators': 300, 'learning_rate': 0.06302137031345638}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:09:46,641] Trial 38 finished with value: 0.9781791013169521 and parameters: {'max_depth': 11, 'n_estimators': 600, 'learning_rate': 0.07638546348602604}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:10:07,631] Trial 39 finished with value: 0.9751454025220796 and parameters: {'max_depth': 12, 'n_estimators': 750, 'learning_rate': 0.016461703038520688}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:10:16,122] Trial 40 finished with value: 0.9753049220074455 and parameters: {'max_depth': 6, 'n_estimators': 1200, 'learning_rate': 0.09672281711180211}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:10:30,023] Trial 41 finished with value: 0.9783232066097003 and parameters: {'max_depth': 12, 'n_estimators': 600, 'learning_rate': 0.05552002653530969}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:10:44,591] Trial 42 finished with value: 0.978268147029267 and parameters: {'max_depth': 12, 'n_estimators': 650, 'learning_rate': 0.0666149555098256}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:10:58,859] Trial 43 finished with value: 0.977882479920809 and parameters: {'max_depth': 11, 'n_estimators': 700, 'learning_rate': 0.04356553396090737}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:11:11,041] Trial 44 finished with value: 0.9780380640921116 and parameters: {'max_depth': 12, 'n_estimators': 550, 'learning_rate': 0.08485069580656585}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:11:22,974] Trial 45 finished with value: 0.9787502166717457 and parameters: {'max_depth': 10, 'n_estimators': 800, 'learning_rate': 0.12765905263601507}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:11:35,009] Trial 46 finished with value: 0.9778147366015907 and parameters: {'max_depth': 10, 'n_estimators': 800, 'learning_rate': 0.1204496996371266}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:11:47,180] Trial 47 finished with value: 0.9771570696584626 and parameters: {'max_depth': 10, 'n_estimators': 850, 'learning_rate': 0.17052349210045134}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:11:55,105] Trial 48 finished with value: 0.978058827357732 and parameters: {'max_depth': 8, 'n_estimators': 750, 'learning_rate': 0.16301855310084076}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:11:58,164] Trial 49 finished with value: 0.9211361373663555 and parameters: {'max_depth': 2, 'n_estimators': 900, 'learning_rate': 0.1309466056884092}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:12:07,250] Trial 50 finished with value: 0.9781570508976704 and parameters: {'max_depth': 9, 'n_estimators': 700, 'learning_rate': 0.09470685441860038}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:12:19,925] Trial 51 finished with value: 0.9782616479583208 and parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.07295012562142769}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:12:30,048] Trial 52 finished with value: 0.9775681063545782 and parameters: {'max_depth': 12, 'n_estimators': 450, 'learning_rate': 0.10590103716570977}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:12:42,180] Trial 53 finished with value: 0.9777635005005583 and parameters: {'max_depth': 11, 'n_estimators': 600, 'learning_rate': 0.05681771263016965}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:12:53,207] Trial 54 finished with value: 0.9781570867691658 and parameters: {'max_depth': 10, 'n_estimators': 700, 'learning_rate': 0.06894406483448977}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:13:05,537] Trial 55 finished with value: 0.9782310210864869 and parameters: {'max_depth': 12, 'n_estimators': 550, 'learning_rate': 0.08435141469205434}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:13:19,499] Trial 56 finished with value: 0.9786174446614818 and parameters: {'max_depth': 11, 'n_estimators': 800, 'learning_rate': 0.11650781211868362}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:13:33,690] Trial 57 finished with value: 0.9778150742156659 and parameters: {'max_depth': 11, 'n_estimators': 800, 'learning_rate': 0.11939643173069463}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:13:47,206] Trial 58 finished with value: 0.9774757847306909 and parameters: {'max_depth': 10, 'n_estimators': 950, 'learning_rate': 0.14534901179990098}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:13:58,425] Trial 59 finished with value: 0.9782677355621129 and parameters: {'max_depth': 9, 'n_estimators': 900, 'learning_rate': 0.12901319580759155}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:14:15,657] Trial 60 finished with value: 0.9782776498104377 and parameters: {'max_depth': 11, 'n_estimators': 1000, 'learning_rate': 0.10675704139766914}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:14:31,802] Trial 61 finished with value: 0.9790376370292974 and parameters: {'max_depth': 12, 'n_estimators': 800, 'learning_rate': 0.092095517102996}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:14:48,596] Trial 62 finished with value: 0.9786673303062138 and parameters: {'max_depth': 12, 'n_estimators': 800, 'learning_rate': 0.07869454111818323}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:15:06,112] Trial 63 finished with value: 0.977715639485233 and parameters: {'max_depth': 12, 'n_estimators': 850, 'learning_rate': 0.07901883352554835}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:15:21,635] Trial 64 finished with value: 0.9781034757641235 and parameters: {'max_depth': 12, 'n_estimators': 750, 'learning_rate': 0.0869266969180914}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:15:36,900] Trial 65 finished with value: 0.978091044180851 and parameters: {'max_depth': 12, 'n_estimators': 750, 'learning_rate': 0.09677611635109777}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:15:50,322] Trial 66 finished with value: 0.9782564138851123 and parameters: {'max_depth': 11, 'n_estimators': 700, 'learning_rate': 0.06353050871575598}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:16:07,388] Trial 67 finished with value: 0.9781880048331395 and parameters: {'max_depth': 12, 'n_estimators': 850, 'learning_rate': 0.09199291750718232}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:16:10,689] Trial 68 finished with value: 0.936369517600825 and parameters: {'max_depth': 4, 'n_estimators': 650, 'learning_rate': 0.04948173281669073}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:16:24,684] Trial 69 finished with value: 0.9790530955337624 and parameters: {'max_depth': 11, 'n_estimators': 750, 'learning_rate': 0.07780584977673026}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:16:39,784] Trial 70 finished with value: 0.9785372296673194 and parameters: {'max_depth': 11, 'n_estimators': 800, 'learning_rate': 0.06760154547247779}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:16:53,797] Trial 71 finished with value: 0.978125264532497 and parameters: {'max_depth': 11, 'n_estimators': 750, 'learning_rate': 0.07393639507444541}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:17:08,228] Trial 72 finished with value: 0.978095143026732 and parameters: {'max_depth': 12, 'n_estimators': 700, 'learning_rate': 0.10261628320414505}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:17:20,680] Trial 73 finished with value: 0.9788003196555384 and parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.07956887457257102}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:17:33,660] Trial 74 finished with value: 0.9781951443157846 and parameters: {'max_depth': 10, 'n_estimators': 850, 'learning_rate': 0.07922887555616505}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:17:49,074] Trial 75 finished with value: 0.9785220929512699 and parameters: {'max_depth': 12, 'n_estimators': 750, 'learning_rate': 0.0903171474152584}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:18:04,238] Trial 76 finished with value: 0.9789894078036214 and parameters: {'max_depth': 11, 'n_estimators': 800, 'learning_rate': 0.06130069559926037}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:18:18,286] Trial 77 finished with value: 0.9786109804069871 and parameters: {'max_depth': 10, 'n_estimators': 900, 'learning_rate': 0.06035351298393799}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:18:31,888] Trial 78 finished with value: 0.9769184387549426 and parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.03665591594176125}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:18:45,735] Trial 79 finished with value: 0.9781778437045223 and parameters: {'max_depth': 11, 'n_estimators': 700, 'learning_rate': 0.052936403817672936}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:18:49,372] Trial 80 finished with value: 0.9545266325607661 and parameters: {'max_depth': 5, 'n_estimators': 600, 'learning_rate': 0.07012265802838805}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:19:05,979] Trial 81 finished with value: 0.9778058974430863 and parameters: {'max_depth': 12, 'n_estimators': 800, 'learning_rate': 0.08063640186661378}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:19:17,914] Trial 82 finished with value: 0.978091727849353 and parameters: {'max_depth': 10, 'n_estimators': 750, 'learning_rate': 0.0658138321986469}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:19:33,358] Trial 83 finished with value: 0.9788626200028393 and parameters: {'max_depth': 11, 'n_estimators': 800, 'learning_rate': 0.0743489232089714}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:19:49,681] Trial 84 finished with value: 0.9789167954564134 and parameters: {'max_depth': 11, 'n_estimators': 850, 'learning_rate': 0.059670311108351796}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:20:07,056] Trial 85 finished with value: 0.9787439644810918 and parameters: {'max_depth': 11, 'n_estimators': 900, 'learning_rate': 0.05751308878713227}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:20:20,858] Trial 86 finished with value: 0.9784485627157952 and parameters: {'max_depth': 10, 'n_estimators': 850, 'learning_rate': 0.04937290643998905}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:20:37,822] Trial 87 finished with value: 0.9782722226641802 and parameters: {'max_depth': 11, 'n_estimators': 850, 'learning_rate': 0.043079759601052744}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:20:56,010] Trial 88 finished with value: 0.9780691594034749 and parameters: {'max_depth': 11, 'n_estimators': 1000, 'learning_rate': 0.07316680487046759}. Best is trial 23 with value: 0.9790548004848416.
[I 2026-08-24 20:21:08,358] Trial 89 finished with value: 0.9788131331647335 and parameters: {'max_depth': 10, 'n_estimators': 750, 'learning_rate': 0.06231322242270983}. Best is trial 23 with value: 0.9790548004848416.

XGB Best parameters: {'max_depth': 11, 'n_estimators': 650, 'learning_rate': 0.08242569290499799}, Best ROC-AUC CV value: 0.9790548004848416

In [13]:
results = []

results.append({
        'Model': 'XGBoost',
        'ROC-AUC': study.best_value,
    })

In [14]:
import lightgbm as lgb

# def objective_lgb(trial):
#     params = {
#         'max_depth': trial.suggest_int('max_depth', 2, 15),
#         'n_estimators': trial.suggest_int('n_estimators', 300, 1500, step=50),
#         'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
#     }
model_lgb = lgb.LGBMClassifier(device='cpu', random_state=42, verbose=-1, max_depth=10, n_estimators=900, learning_rate=0.09)
model_lgb.fit(X_train.to_numpy(), y_train.to_numpy())
preds_lgb = model_lgb.predict_proba(X_val.to_numpy())[:, 1]
lgb_score = roc_auc_score(y_val.to_numpy(), preds_lgb)
    # return roc_auc_score(y_val.to_numpy(), preds_lgb)

# study_lgb = optuna.create_study(direction='maximize')
# study_lgb.optimize(objective_lgb, n_trials=100)
# print(f'LGBM Best parameters: {study_lgb.best_params}, Best ROC-AUC value: {study_lgb.best_value}')
print(lgb_score)

0.9704649172226942

In [15]:
results.append({
        'Model': 'Light GBM',
        'ROC-AUC': lgb_score,
    })

In [16]:
import catboost as cb

# def objective_cb(trial):
#     params = {
#         'max_depth': trial.suggest_int('max_depth', 2, 15),
#         'n_estimators': trial.suggest_int('n_estimators', 50, 1000, step=50),
#         'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
#     }
cb_model = cb.CatBoostClassifier(task_type="GPU", random_state=42, verbose=0, max_depth=10, n_estimators=900, learning_rate=0.09)
cb_model.fit(X_train.to_pandas(), y_train.to_pandas())
cb_preds = cb_model.predict_proba(X_val.to_pandas())[:, 1]
cb_score = roc_auc_score(y_val.to_numpy(), cb_preds)
# return roc_auc_score(y_val.to_numpy(), preds)

# study_cb = optuna.create_study(direction='maximize')
# study_cb.optimize(objective_cb, n_trials=50, n_jobs=1)
# print(f'CatBoost Best parameters: {study_cb.best_params}, Best ROC-AUC value: {study_cb.best_value}')
print(cb_score)

Warning: less than 75% GPU memory available for training. Free: 5770 Total: 8191.5

0.9669887087145963

In [17]:
results.append({
        'Model': 'CatBoost',
        'ROC-AUC': cb_score,
    })

In [18]:
cd.DataFrame(results)

       Model   ROC-AUC
0    XGBoost  0.979055
1  Light GBM  0.970465
2   CatBoost  0.966989

## 7. Blending
Простое усреднение предсказаний позволяет сгладить переобучение отдельных моделей и повысить итоговый ROC-AUC на лидерборде. При этом, взвешенное усреднение дало немного лучший результат на LB, ввиду лучшего roc_auc_score у XGBoost.

In [19]:
xgb_model = xgb.XGBClassifier(max_depth=10, n_estimators=800, learning_rate=0.105, tree_method='hist', device='cuda', random_state=42)
xgb_model.fit(X_train, y_train)
xgb_preds = xgb_model.predict_proba(X_val)[:, 1]

blend_preds = xgb_preds * 0.5 + preds_lgb * 0.25 + cb_preds * 0.25
blend_score = roc_auc_score(y_val.to_numpy(), blend_preds)

In [20]:
results.append({
        'Model': 'Blending',
        'ROC-AUC': blend_score,
    })

In [21]:
results[3]['ROC-AUC'] = blend_score
cd.DataFrame(results)

       Model   ROC-AUC
0    XGBoost  0.979055
1  Light GBM  0.970465
2   CatBoost  0.966989
3   Blending  0.976632

In [25]:
sample_df = pd.read_csv(r'../data/final/sample_submission.csv')
sample_df['isFraud'] = xgb_model.predict_proba(test_trans)[:, 1] * 0.5 + model_lgb.predict_proba(test_trans)[:, 1] * 0.25 + cb_model.predict_proba(test_trans.to_numpy())[:, 1] * 0.25

sample_df.to_csv('../data/final/blending.csv', index=False)